### ISSUE TITLE
LevelDB usage is ready to ship

### ISSUE THREAD

**Issue by macgregordennis** [turinginc/credo-core-node#290]

**Comment by macgregordennis** [comment]
This should be resolved by further improvements to https://github.com/turinginc/credo-core-node/pull/277.

**Comment by AlimovSV** [comment]
@macgregordennis Looks like we have a leaks with MPT/ExlevelDB/LevelDB stack. I believe that this  is a source of the `:db_inaccessable` problem. Thus, `leveldb` does not close an internal files (like `state/sst_0/072012` or `state/072013.log`) and after some time later the count of opened files reaches `ulimit -n` and `leveldb` fall to comatose. I've checked our code and and I don't see the case where we do not close LevelDB reference. If you will have a chance please try to run the `mix bench bench/credo_core_node/state/calculate_world_state_with_block_and_transactions.exs` script (`close-leveldb` branch). Depending on your current `ulimit -n` (the default is 256) after 300-400 iterations it fails for me. Ivan has `ulimit -n` = 4096 and and works successfully with all 10000 iterations. But 1) it may fail after 20, 30, 40000 iteration, 2) we should work with default ulimit, because we have embedded mode (in the wallet). At the moment I have no idea what the reason is, I tried to reproduce these leaks without MPT stack, just using the eleveldb but it works fine.

**Comment by AlimovSV** [comment]
I tried to upgrade eleveldb to 
```
      # Riak KV 2.9.0 - Release
      {:eleveldb,
       github: "basho/eleveldb",
       ref: "72f28a1f1b8afd0ed819985ca2f06ebf0e1ed8cc",
       manager: :rebar,
       override: true},
```
But I observe the leaks anyway

**Comment by malroc** [comment]
> At the moment I have no idea what the reason is, I tried to reproduce these leaks without MPT stack, using the eleveldb only but it works fine.

@AlimovSV I'll take a look after fixing the connection issue. I think we can try to fork either MPT or LevelDB and use our own branch depending on what causes the problem.
